version: '3.7'

services:
  thermobeacon: # Thermobeacon server to collect data from the thermobeacons.
    image: stefanrichterhuber/thermobeaconserver:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    privileged: true # Necessary to have enough permissions to access dbus with bluetooth devices of the host
    environment:
      - TZ=Europe/Berlin # Optional set timezone for proper calculation of the next invocation from cron expression
      - RUST_LOG=debug # Optional set debug level to error/warn/info/debug to resolve connection issues
      - APP_DEVICES[0]_MAC=78:9f:00:00:05:8a
      - APP_DEVICES[0]_NAME=Plant
      - APP_DEVICES[0]_TOPIC=home/ThermoBeacon/Plant
      - APP_CRON=*/1 * * * *
      - APP_MQTT_URL=tcp://mosquitto:1883
      #- APP_MQTT_USERNAME=telegraf
      #- APP_MQTT_PASSWORD=telegraf
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket # Necessary to access the bluetooth devices of the host

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  controller:
    image: node:23-alpine
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=http://mosquitto:1883
    volumes:
      - ./controller:/home/node/app
    working_dir: /home/node/app
    ports:
      - '3000:3000'
    command: bash -c "npm i && npm start"
